///******************************** User_library *********************************
//* 文件名 	: STM32_SDCard.H
//* 作者   	: wegam@sina.com
//* 版本   	: V
//* 日期   	: 2016/01/01
//* 说明   	: 
//********************************************************************************
//* THE PRESENT FIRMWARE WHICH IS FOR GUIDANCE ONLY AIMS AT PROVIDING CUSTOMERS
//* WITH CODING INFORMATION REGARDING THEIR PRODUCTS IN ORDER FOR THEM TO SAVE TIME.
//* AS A RESULT, STMICROELECTRONICS SHALL NOT BE HELD LIABLE FOR ANY DIRECT,
//* INDIRECT OR CONSEQUENTIAL DAMAGES WITH RESPECT TO ANY CLAIMS ARISING FROM THE
//* CONTENT OF SUCH FIRMWARE AND/OR THE USE MADE BY CUSTOMERS OF THE CODING
//* INFORMATION CONTAINED HEREIN IN CONNECTION WITH THEIR PRODUCTS.
//*******************************************************************************/


//#ifndef __STM32_SPI_H
//#define __STM32_SPI_H

//#include "stm32f10x_spi.h"
//#include "stm32f10x_gpio.h"
//#include "stm32f10x_rcc.h"
//#include "stm32f10x_dma.h"
//#include "stm32f10x_nvic.h"



//#include	"stdio.h"							//用于printf
//#include	"string.h"						//用于printf
//#include	"stdarg.h"						//用于获取不确定个数的参数
//#include	"stdlib.h"						//malloc动态申请内存空间


//typedef struct
//{
//	GPIO_TypeDef* GPIO_NSS;
//  u16 SPI_NSSP;									//设置方向				（2线全双工、2线只接收、一线发送、一线接收）
//	GPIO_TypeDef* GPIO_SCK;
//  u16 SPI_SCKP;									//模式         	（从或主设备）
//	GPIO_TypeDef* GPIO_MISO;
//  u16 SPI_MISOP;								//宽度         	（8或16位）
//	GPIO_TypeDef* GPIO_MOSI;
//  u16 SPI_MOSIP;								//时钟极性     	（低或高）

////	SPI_InitTypeDef SPI_Set;
//	
//}SPI_ConfTypeDef;


//void SPIT_Configuration(SPI_TypeDef* Port);							//SPI常规配置
//void SPIT_PinSet(SPI_TypeDef* SPIx);													//SPI管脚配置及初始化

//u8 SPIT_SendByte(u8 byte);
//#endif

