#ifndef __CD4511BM_TEST_H
#define __CD4511BM_TEST_H

//#include "STM32_USART.H"
//#include "STM32_TIM.H"
//#include "STM32_DMA.H"
//#include "STM32_PWM.H"
//#include "STM32_GPIO.H"
//#include "STM32_ADC.H"
//#include "STM32_DAC.H"
//#include "STM32_CAN.H"
//#include "STM32_PWM.H"
//#include "STM32_CD4511BM.H"
//#include "STM32_GPIO.H"


void CD4511BM_TEST_Configuration(void);
void CD4511BM_TEST_Server(void);

//void SEG_DISPALY(u16 time);
//void CD4511BM_KEY_FUNC(void);



#endif

