#ifndef __SPI_TEST_H
#define __SPI_TEST_H

//#include "STM32_USART.H"
//#include "STM32_TIM.H"
//#include "STM32_DMA.H"
//#include "STM32_PWM.H"
//#include "STM32_GPIO.H"
//#include "STM32_ADC.H"
//#include "STM32_DAC.H"
//#include "STM32_SPI.H"


//typedef enum {DISABLE1 = 2, ENABLE1 = 3} FunctionalState1;
//#define IS_FUNCTIONAL_STATE1(STATE) (((STATE) == DISABLE1) || ((STATE) == ENABLE1))

//typedef enum {DISABLE2 = 4, ENABLE2 = 5} FunctionalState2;
//#define IS_FUNCTIONAL_STATE2(STATE) (((STATE) == DISABLE2) || ((STATE) == ENABLE2))

void SPI_TEST_Configuration(void);
void SPI_TEST_Server(void);




#endif

